services:
  web: 
    image: nginx:stable-alpine3.21-perl
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - quiz-network
  
  php-fpm:
    build: .
    volumes:
      - ./src:/app/src
    networks: 
      - quiz-network

  db:
    image: mysql:9.5.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.develop/mysql_init:/docker-entrypoint-initdb.d
    networks:
      - quiz-network
    
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: dracula
    networks:
      - quiz-network
    depends_on:
      - db

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql_data: