services:
  web: 
    image: nginx:stable-alpine3.21-perl
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - quiz-network
  
  php-fpm:
    image: php:8.1.33-fpm
    volumes:
      - ./src:/app
    networks: 
      - quiz-network

networks:
  quiz-network:
    driver: bridge